packages:
  - .

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@algoux/standard-ranklist-utils@0.3.3'
  - '@algoux/standard-ranklist-renderer-component-core@0.6.4'
  - '@algoux/standard-ranklist-renderer-component-styles@0.6.2'
  - '@algoux/standard-ranklist-renderer-component-svelte@0.6.5'

onlyBuiltDependencies:
  - esbuild
